### ISSUE TITLE
doesn`t work on nova v2.0.0

### ISSUE THREAD

**Issue by watermelon-brother** [inspheric/nova-defaultable-fields#10]
Method Laravel\Nova\Http\Requests\NovaRequest::isCreateOrAttachRequest does not exist

**Comment by kitbs** [comment]
Hi @watermelon-brother 

Yes, I can see that method and setting editMode on the request was added to Nova in v2.0.1. 

v2.0.0 is now 6 months old. Is there a reason you cannot update your Nova install?

Without that code, I can't distinguish between create and update requests.

**Comment by watermelon-brother** [comment]
@kitbs  Everything is ok when I update to the nova's latest version,thank you

**Comment by kitbs** [comment]
Glad to hear you got it to work.
